name: Python CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 .

      - name: Run tests with pytest
        run: pytest

      - name: Generate coverage report
        run: |
          coverage run -m pytest
          coverage report

  deploy_job:
    runs-on: ubuntu-latest
    needs: build # Chạy sau khi job 'build' thành công
    if: github.ref == 'refs/heads/main' # Chỉ deploy khi trên nhánh main
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          echo "Deploying to server..."
          scp -r . user@192.168.1.100:/var/www/myapp
          ssh user@192.168.1.100 "cd /var/www/myapp && ./restart.sh"
