name: Simple Advanced CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black pytest pytest-cov

      - name: Format code with Black
        run: black .

      - name: Run tests with coverage
        run: |
          pytest --cov=./ --cov-report=term-missing

      - name: Check test coverage
        run: |
          coverage report --fail-under=80
